### ISSUE TITLE
Add support for the Variant coq keyword

### ISSUE THREAD

**Issue by ddemange** [xavierleroy/coq2html#6]
It would be nice to have the `Variant` keyword recognized, and highlighted as the `Inductive` keyword in the output html.
Currently, this doesn't seem to be the case. The fix may be as simple as adding it to the [coq_keywords](https://github.com/xavierleroy/coq2html/blob/4e4c7f20bbd98cca999b0bc589c2896ed692791e/coq2html.mll#L112) set.

**Comment by xavierleroy** [comment]
Sure.  Commit 466627c updates the lists of keywords and tactics, including Variant.

**Comment by ddemange** [comment]
Great, thanks!
